name: iy
favicon: null
layout_spectrum: 0.7022558683529496
typography_spectrum: 0.43215523287653923
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c5a13e'
    - '#005cc4'
    - '#161712'
    - '#b71f34'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
